
Vagrant.configure("2") do |config|
 config.vm.define "slave01" do |slave01|
  slave01.vm.box = "bento/centos-7.3"
  slave01.vm.hostname = "slave01"
 end

 config.vm.define "slave02" do |slave02|
  slave02.vm.box = "bento/fedora-26"
  slave02.vm.hostname = "slave02"
end
end


