
Vagrant.configure("2") do |config|
 config.vm.define "sla1" do |sla1|
  sal1.vm.box = "bento/centos-7.3"
  sla1.vm.hostname = "sla1"
 end

 config.vm.define "sla2" do |sla2|
  sla2.vm.box = "bento/fedora-26"
  sla2.vm.hostname = "sla2"
end
end


